# Generated by Django 3.0.8 on 2020-09-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='section',
        ),
    ]
